name: Blog 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
google_analytics: UA-84003728-2
comments:
    provider: disqus
disqus.shortname: aaupov-github-io
comments: true
plugins:
  - jekyll-toc
